dist: precise
sudo: false

language: cpp
compiler: clang

# Install dependencies
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - lib32stdc++6
    - lib32z1-dev
    - libc6-dev-i386
    - linux-libc-dev
    - g++-multilib
    - g++-4.8
  cache:
    directories:
    - ../mysql-5.0

# Set the build environment
env:
  global:
  - LLVM_ARCHIVE_URI=http://sourcemod.net/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz

before_install:
  - wget -nc $LLVM_ARCHIVE_URI -O $HOME/clang+llvm.tar.xz
  - mkdir -p $HOME/clang+llvm
  - tar -xf $HOME/clang+llvm.tar.xz -C $HOME/clang+llvm --strip-components 1
  - export PATH=$HOME/clang+llvm/bin:$PATH
  - CC=clang-3.8 CXX=clang-3.8

install:
  - git clone --branch 1.10-dev https://github.com/alliedmodders/metamod-source mmsource-1.10
  - git clone --recursive --branch 1.7-dev https://github.com/alliedmodders/sourcemod sourcemod
  - rm -rf ./sourcemod/sourcepawn/*
  - git clone --branch master https://github.com/alliedmodders/sourcepawn ./sourcemod/sourcepawn
  - git clone --mirror https://github.com/alliedmodders/hl2sdk hl2sdk-proxy-repo
  - git clone --branch l4d2 hl2sdk-proxy-repo hl2sdk-l4d2
  - git clone --branch master https://github.com/alliedmodders/ambuild ambuild
  #- bash sourcemod/tools/checkout-deps.sh
    
before_script:
  - cd ambuild
  - python setup.py build
  - python setup.py install --user
  - cd ..
  - mkdir build && cd build
  - PATH="~/.local/bin:$PATH"
  - python ../configure.py --enable-optimize --sdks=present --sdks=l4d2

script: ambuild

# Deployment phase
before_deploy:
  - env GZIP=-9 tar cvzf signals.tar.gz --directory="./package" .

deploy:
  provider: releases
  api_key:
    secure: "GGzbvz0wILEuSIvuv2+/0Ym02nModPxM6ZCNUc1ewLv7eEns7eYnhfHCcMxFj+PV4sJgh5QMnLRfr1plekPsFVCSLMTGDWp7cfzVSXHMPURf2oR3+Qm1Nx9zfDMVML4m/ljGO4J1cMbkdZcwn/CLN2x0nnbrxk1m9uS+u5N5FophFbCAOvOHzfkX41cCh4/Efupdge7dw5ZKgLEKlQ8al+G8mnWTKxKB6New6eH1pMU7BTX4z5edlG5gcrjpEM5FYL5ZpJm0qB7DIuOvJHHKJ60UFK5Tc66/fPe742QuTELXg9m27K93z0jOxKbrjlUK4pRhB9GIW4MJbdI8kpb1LGtA0vA33UGfnYB+FsC7gseECCTRJ+5cntHAB6PVn0AqgeonWBvGHqGcHav5ez+WZBMKdPdtsLK51dzgilDbIfKcKXH+pWPa9F5BlYcDI+tuekwqBeK4VDGAC+Nw4t8FM4ikGB8wmnh1Nwo2cYDtmJcq7tsdPc4c9okwgbGhUAG4kQob+bATBuoE8P2YJrTRJ9ucd/cgxGzvDKrGiMImeR9FqggtQPj+keW4UGavKmyoeSCnWP+4w4Yuy5M7QwTTsLtVbjMMYpfqx5LjAIS1UIujaeJhhUGZhIyS7en+KXZAeGH4Z26W9bD/Sq2tXLE6CQa6GnQPD1GIkPDO7JdIsww="
  file: "signals.tar.gz"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true

# Notifications
notifications:
  email: false
  