dist: trusty
sudo: false
language: cpp
addons:
  apt:
    packages:
    - g++-multilib
compiler:
  - clang
before_install:
- git clone --depth=1 --branch 1.10-dev https://github.com/alliedmodders/metamod-source mmsource-1.10
- git clone --depth=1 --recursive --branch=1.8-dev https://github.com/alliedmodders/sourcemod sourcemod
- git clone --mirror https://github.com/alliedmodders/hl2sdk hl2sdk-proxy-repo
- git clone --branch l4d2 hl2sdk-proxy-repo hl2sdk-l4d2
- git clone --depth=1 --branch master https://github.com/alliedmodders/ambuild ambuild
install:
- cd ambuild && python setup.py install --user
- cd $TRAVIS_BUILD_DIR
- git fetch --unshallow || true
before_script:
- mkdir build && cd build
- python ../configure.py --enable-optimize --sdks=present
script: ambuild
before_deploy:
- env GZIP=-9 tar cvzf signals.tar.gz --directory="./package" .
deploy:
  provider: releases
  api_key:
    secure: Ko6fdnlk608m+qiND/Ae4vFRROmFFRbPLa0tqZdmcTx5nOFEgSZOy1NTYN8Dce6ziDg7KaBecGTJNJombPrZPFs/58zV5LYEyxBH+Tifx7m4QM3RR3fN2XPGq4BM4GYaqjzw6TzPjxNtrk6HJ++8V7wSsRwhKFx2G5cuA2XjQ+lc3aw6+LopzHBvcxvJvlC6DexwqY6ap5ZybvUo6lvhJPAihYO4UK2TZ/u292Q2YK1BDP/UKBhClrEI2GC3pFw2AoYDnznZji8yHwQCE3gEyfISs8xLNFzqJ14Nz1hYKzKkH1g7PKI+R4MLbrPgexeZNeebR/3Rqyg4WNMX6ICeA35xSguSD7C+Oc+hv/sZw3o4TEjLafd1i3d10qVmnllcdVj9u8ScVg06T4BukPyWA0qJHdu2F1Ol8z6IDdcAbz5mQvu7pRHzeiXhUJUWd1jhwUGt73k2GOeNjdtB5Y9Mb9ywk3Uu3VfAe2gvsPTk4gArZXWLVVwXt77kbDSogp2pN+2F0O+U1i5e1fKJBiPwiv0N88Mc939pMVXr6nun8Qh5+GaVKGIY+z9mgmLg2wpf7pVayEiLOz/d2ushLWMg8qWvXoZgTWqwH/u3DOInpEN2DWva/tbVCFtOopaXHV1/EEgHgoNvyUP0C7KqsGsskFlKKiVAjvW+6cR85HSduIY=
  file: signals.tar.gz
  skip_cleanup: true
  on:
    repo: Robotex/signals-sm
